using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class charcterController : MonoBehaviour
{
    public float speed = 1.0f;                // Karakterin hýzý
    private Rigidbody2D r2d;
    private SpriteRenderer _spriteRenderer;
    private Animator _animator;
    private Vector3 charPos;
    [SerializeField] private GameObject _camera;   // Kamera nesnesi

    private void Start()
    {
        r2d = GetComponent<Rigidbody2D>();
        _spriteRenderer = GetComponent<SpriteRenderer>();
        _animator = GetComponent<Animator>();
        charPos = transform.position;
    }

    private void Update()
    {
        // Boþluk tuþuna basýlýrsa hýzý ayarla
        if (Input.GetKey(KeyCode.Space))
        {
            speed = 1.0f;
        }
        else
        {
            speed = 0.0f;
        }

        // Yatay hareketi isle ve karakter pozisyonunu güncelle
        charPos = new Vector3(charPos.x + (Input.GetAxis("Horizontal") * Time.deltaTime), charPos.y);
        transform.position = charPos;

        // Hýzý ve animasyonlarý iþle
        if (Input.GetAxis("Horizontal") == 0.0f)
        {
            _animator.SetFloat("speed", 0.0f);
        }
        else
        {
            _animator.SetFloat("speed", 1.0f);
        }

        // Karakterin yüzünü çevir
        if (Input.GetAxis("Horizontal") > 0.01f)
        {
            _spriteRenderer.flipX = false;
        }
        else if (Input.GetAxis("Horizontal") < -0.01f)
        {
            _spriteRenderer.flipX = true;
        }
    }

    private void LateUpdate()
    {
        // Kamera pozisyonunu güncelle (istege baðlý)
        // _camera.transform.position = new Vector3(charPos.x, charPos.y, charPos.z - 1.0f);
    }
}
